POST https://localhost/cairnsgames/php/kloko/api.php/user_location
Content-Type: application/json
Authorization: Bearer Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOm51bGwsInN1YiI6bnVsbCwiYXVkIjpudWxsLCJleHAiOjE4MTA0NzE0NTcsIm5iZiI6MTc0OTk5MTQ1NywiaWF0IjoxNzQ5OTkxNDU3LCJqdGkiOiJ7NjcxMzdDMzItN0YxMC1BQzZGLTVFMjQtMUQzMzE0NkFEQzczfSIsImRhdGEiOnsiaWQiOjIxLCJ1c2VybmFtZSI6IjAiLCJmaXJzdG5hbWUiOiJXaWxsaWFtIiwibGFzdG5hbWUiOiJDYWlybnMiLCJyb2xlIjoyLCJwZXJtaXNzaW9ucyI6W3sibmFtZSI6IkF1dGgiLCJwZXJtaXNzaW9uIjoiWUVTIn0seyJuYW1lIjoiQ2FsZW5kYXIiLCJwZXJtaXNzaW9uIjoiWUVTIn0seyJuYW1lIjoiRXZlbnRzIiwicGVybWlzc2lvbiI6IllFUyJ9LHsibmFtZSI6IkltcGVyc29uYXRlVXNlciIsInBlcm1pc3Npb24iOiJZRVMifSx7Im5hbWUiOiJMb3lhbHR5IiwicGVybWlzc2lvbiI6IllFUyJ9LHsibmFtZSI6Ik1lbWJlcnNoaXBBZG1pbmlzdHJhdGlvbiIsInBlcm1pc3Npb24iOiJOTyJ9LHsibmFtZSI6Ik9yZGVycyIsInBlcm1pc3Npb24iOiJZRVMifSx7Im5hbWUiOiJQYXJ0bmVyIiwicGVybWlzc2lvbiI6IllFUyJ9LHsibmFtZSI6IlN0b3JlIiwicGVybWlzc2lvbiI6IllFUyJ9LHsibmFtZSI6IlRlbmFudCIsInBlcm1pc3Npb24iOiJOTyJ9XX19.NzE5NTUwNzUxYzA0ZDM2M2MzNGM3MjFkODZjMjFhNmMwYTcwMWExNjQ0OTk0YjJhNTkzYjExZGM2ZGY2OTk1NQ

{
  "user_id": 21,
  "location_id": 1013
}