name: Publish Template App to website

on: 
  push:
    branches:    
      - main 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm ci

  # publish:
  #   needs: build
  #   runs-on: ubuntu-latest
  #   permissions:
  #     packages: write
  #     contents: write
  #   steps:
  #     - uses: actions/checkout@v3
  #     - run: git config --global user.name ${{ secrets.CG_USERNAME }}
  #     - run: git config --global user.email ${{ secrets.CG_USEREMAIL }}
  #     - uses: actions/setup-node@v3
  #       with:
  #         node-version: 16
  #         token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
  #         registry-url: https://npm.pkg.github.com/
  #         scope: "@cairnswm"
  #     # - run: cd library/tenant
  #     # - name: Bump version
  #     #   run: npm version patch -w @cairnsgames/tenant --git-tag-version -m "[RELEASE] %s"
  #     # - run: |
  #     #     current_datetime=$(date +"%Y-%m-%d %H:%M:%S")
  #     #     jq --arg dt "$current_datetime" '.message = $dt' ./library/tenant/package.json > temp.json && mv temp.json ./library/tenant/package.json
  #     # - run: cd ../..
  #     # - run: git add .
  #     # - run: git push origin main --follow-tags --force
  #     - run: npm ci -w @cairnsgames/tenant
  #     - run: npm run build -w @cairnsgames/tenant
  #     - run: npm publish -w @cairnsgames/tenant --@cairnsgames:registry=https://npm.pkg.github.com/
  #       env:
  #         NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
          
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x]
    
    steps:
    - name: Get latest code
      uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@master
      with:
        node-version: ${{ matrix.node-version }}
    
    - name: Build Project 
      run: npm ci
    - name: build library
      run: npm run build
    
    - name: Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.3.3
      with:
        server: ${{ vars.CG_SERVER }}
        username: ${{ vars.CG_FTP_USERNAME }}
        password: ${{ secrets.CG_FTP_PASSWORD }}
        local-dir: ./dist/
        server-dir: ${{ vars.SERVER_DIR }}