name: Publish Template App to website

on:
  push:
    branches:
      - main

jobs:
  build-main-site:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - run: npm ci
      - name: Build Main Site
        run: npm run build
      - name: Deploy Main Site
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          server: ${{ vars.CG_SERVER }}
          username: ${{ vars.CG_FTP_USERNAME }}
          password: ${{ secrets.CG_FTP_PASSWORD }}
          local-dir: ./dist/
          server-dir: ${{ vars.SERVER_DIR }}

  build-zharo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Change directory to mini project
        run: cd packages/zharo
      - name: Install dependencies for mini project
        run: npm ci
        working-directory: packages/zharo
      - name: Build mini project
        run: npm run build
        working-directory: packages/zharo
      - name: Deploy Zharo
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          server: ${{ vars.CG_SERVER }}
          username: ${{ vars.CG_FTP_USERNAME }}
          password: ${{ secrets.CG_FTP_PASSWORD }}
          local-dir: ./packages/zharo/dist/
          server-dir: /zharo/

  deploy-zharo-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Modify index.html in test directory
        run: |
          sed -i 's|../dist/zharo.js|https://cairnsgames.co.za/zharo/zharo.js|g' packages/zharo/test/index.html
      - name: Deploy Modified Test Directory
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          server: ${{ vars.CG_SERVER }}
          username: ${{ vars.CG_FTP_USERNAME }}
          password: ${{ secrets.CG_FTP_PASSWORD }}
          local-dir: ./packages/zharo/test/
          server-dir: /zharo/test/

  build-kloko:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Change directory to mini project
        run: cd packages/kloko
      - name: Install dependencies for mini project
        run: npm ci
        working-directory: packages/kloko
      - name: Build mini project
        run: npm run build
        working-directory: packages/kloko
      - name: Deploy Zharo
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          server: ${{ vars.CG_SERVER }}
          username: ${{ vars.CG_FTP_USERNAME }}
          password: ${{ secrets.CG_FTP_PASSWORD }}
          local-dir: ./packages/kloko/dist/
          server-dir: /kloko/
