name: Publish Template App to website

on:
  push:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      # Checkout repository once and install root dependencies
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Install Root Dependencies
        run: npm ci
        working-directory: ./projects/just.dance  # Set correct working directory

  build-juztdance:
    runs-on: ubuntu-latest
    needs: setup  # This job depends on the setup job finishing
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Install JuztDance Dependencies
        run: npm ci
        working-directory: ./projects/just.dance

      - name: Build JuztDance Site
        run: npm run build
        working-directory: ./projects/just.dance

      - name: Deploy JuztDance Site
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          server: ${{ vars.JD_SERVER }}
          username: ${{ vars.JD_FTP_USERNAME }}
          password: ${{ secrets.JD_FTP_PASSWORD }}
          local-dir: ./projects/just.dance/dist/
          server-dir: /

  build-zharo:
    runs-on: ubuntu-latest
    needs: setup  # Wait for setup job to complete
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Zharo Dependencies
        run: npm ci
        working-directory: ./packages/zharo

      - name: Build Zharo
        run: npm run build
        working-directory: ./packages/zharo

      - name: Deploy Zharo
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          server: ${{ vars.CG_SERVER }}
          username: ${{ vars.CG_FTP_USERNAME }}
          password: ${{ secrets.CG_FTP_PASSWORD }}
          local-dir: ./packages/zharo/dist/
          server-dir: /zharo/

  deploy-zharo-test:
    runs-on: ubuntu-latest
    needs: build-zharo  # This job depends on build-zharo to finish first
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Modify and Deploy Zharo Test Directory
        run: |
          sed -i 's|../dist/zharo.js|https://cairnsgames.co.za/zharo/zharo.js|g' ./packages/zharo/test/index.html
      - name: Deploy Modified Test Directory
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          server: ${{ vars.CG_SERVER }}
          username: ${{ vars.CG_FTP_USERNAME }}
          password: ${{ secrets.CG_FTP_PASSWORD }}
          local-dir: ./packages/zharo/test/
          server-dir: /zharo/test/

  build-kloko:
    runs-on: ubuntu-latest
    needs: setup  # Waits for setup job to complete
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Kloko Dependencies
        run: npm ci
        working-directory: ./packages/kloko

      - name: Build Kloko
        run: npm run build
        working-directory: ./packages/kloko

      - name: Deploy Kloko
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          server: ${{ vars.CG_SERVER }}
          username: ${{ vars.CG_FTP_USERNAME }}
          password: ${{ secrets.CG_FTP_PASSWORD }}
          local-dir: ./packages/kloko/dist/
          server-dir: /kloko/
