name: Publish Template App to website

on:
  push:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      # Checkout repository only once and install dependencies
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Install Dependencies
        run: npm ci

  build-juztdance:
    runs-on: ubuntu-latest
    needs: setup   # Ensures this job waits for the setup job to finish
    steps:
      - name: Build JuztDance Site
        run: npm run build
      - name: Deploy JuztDance Site
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          server: ${{ vars.JD_SERVER }}
          username: ${{ vars.JD_FTP_USERNAME }}
          password: ${{ secrets.JD_FTP_PASSWORD }}
          local-dir: ./dist/
          server-dir: /

  build-zharo:
    runs-on: ubuntu-latest
    needs: setup   # This job will also wait for the setup to finish
    steps:
      - name: Build Zharo
        run: npm run build
        working-directory: ./packages/zharo
      - name: Deploy Zharo
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          server: ${{ vars.CG_SERVER }}
          username: ${{ vars.CG_FTP_USERNAME }}
          password: ${{ secrets.CG_FTP_PASSWORD }}
          local-dir: ./packages/zharo/dist/
          server-dir: /zharo/

  deploy-zharo-test:
    runs-on: ubuntu-latest
    needs: build-zharo   # This job depends on build-zharo to finish first
    steps:
      - name: Modify and Deploy Zharo Test Directory
        run: |
          sed -i 's|../dist/zharo.js|https://cairnsgames.co.za/zharo/zharo.js|g' ./packages/zharo/test/index.html
      - name: Deploy Modified Test Directory
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          server: ${{ vars.CG_SERVER }}
          username: ${{ vars.CG_FTP_USERNAME }}
          password: ${{ secrets.CG_FTP_PASSWORD }}
          local-dir: ./packages/zharo/test/
          server-dir: /zharo/test/

  build-kloko:
    runs-on: ubuntu-latest
    needs: setup   # Wait for setup before building Kloko
    steps:
      - name: Build Kloko
        run: npm run build
        working-directory: ./packages/kloko
      - name: Deploy Kloko
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          server: ${{ vars.CG_SERVER }}
          username: ${{ vars.CG_FTP_USERNAME }}
          password: ${{ secrets.CG_FTP_PASSWORD }}
          local-dir: ./packages/kloko/dist/
          server-dir: /kloko/
